server:
  port: 80

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

zuul:
  routes:
    route-name:
      service-id: DATABASE
      path: /database
    webbase:
      service-id: WEBBASE
      path: /webbase