server:
  port: 80

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka

zuul:
  routes:
    route-name: #路由别名，无其他意义，与例1效果一致
      service-id: DATABASE
      path: /database